name = "crons"
main = "src/index.ts"
compatibility_date = "2024-04-03"

compatibility_flags = [ "nodejs_compat" ]

logpush = true
workers_dev = false

[triggers]
crons = [
    "0 0 1 1,7 *",
    "0 0 1 7 *",
    "0 2 * * *",
    "0 16 * * *"
]

[dev]
port = 8000


[[hyperdrive]]
binding = "HYPERDRIVE"
id = "09d5c9c4031c40af8f2553d088037367"
localConnectionString = "postgres://postgres:postgres@localhost:5432/echo-web" # Change if needed
