#:schema node_modules/wrangler/config-schema.json
name = "crons"
main = "src/index.ts"
compatibility_date = "2024-04-03"

compatibility_flags = [ "nodejs_compat" ]

#logpush = true
workers_dev = false

[[routes]]
pattern = "crons.echo-webkom.no"
custom_domain = true

[triggers]
crons = [
    "0 0 1 1,7 *",
    "0 0 1 7 *",
    "0 2 * * *",
    "0 16 * * *"
]

[dev]
port = 8000
