name = "crons"
main = "src/index.ts"
compatibility_date = "2023-12-01"

compatibility_flags = [ "nodejs_compat" ]

[triggers]
crons = [
    "0 0 1 1,7 *",
    "0 0 1 7 *",
    "0 2 * * *",
    "0 17 * * *"
]

[dev]
port = 8000
