name = "crons"
main = "src/index.ts"
compatibility_date = "2023-12-01"

compatibility_flags = [ "nodejs_compat" ]

logpush = true
workers_dev = false

[triggers]
crons = [
    "0 0 1 1,7 *",
    "0 0 1 7 *",
    "0 2 * * *",
    "0 16 * * *"
]

[dev]
port = 8000
