#:schema node_modules/wrangler/config-schema.json
name = "echogram"
main = "src/index.ts"
compatibility_date = "2024-04-03"

compatibility_flags = [ "nodejs_compat" ]

#logpush = true
workers_dev = false

[[routes]]
pattern = "echogram.echo-webkom.no"
custom_domain = true

[[r2_buckets]]
binding = "R2"
bucket_name = "avatars"
#jurisdiction = "eu"

[dev]
port = 8001
