name = "echogram"
main = "src/index.ts"
compatibility_date = "2024-09-02"
compatibility_flags = [ "nodejs_compat" ]

#logpush = true
workers_dev = false

[observability]
enabled = true
head_sampling_rate = 1


[[routes]]
pattern = "echogram.echo-webkom.no"
custom_domain = true


[[r2_buckets]]
binding = "R2"
bucket_name = "avatars"
#jurisdiction = "eu"


[dev]
port = 8001
