#:schema node_modules/wrangler/config-schema.json
name = "kaffe"
main = "src/index.ts"
compatibility_date = "2024-04-03"

compatibility_flags = [ "nodejs_compat" ]

#logpush = true
workers_dev = false

[[routes]]
pattern = "kaffe.echo-webkom.no"
custom_domain = true

[[kv_namespaces]]
binding = "KV"
id = "1215f919e5a049cb9b2f90b6a2e5d7a2"

[dev]
port = 8002
