name = "kaffe"
main = "src/index.ts"
compatibility_date = "2024-04-03"

compatibility_flags = [ "nodejs_compat" ]

logpush = true
workers_dev = false

[[kv_namespaces]]
binding = "KV"
id = "071f5174773f4069a8e34879546d0480"

[dev]
port = 8002
