#:schema node_modules/wrangler/config-schema.json
name = "boomtown"
main = "src/index.ts"
compatibility_date = "2024-04-03"

compatibility_flags = [ "nodejs_compat" ]

#logpush = true
workers_dev = false

[[routes]]
pattern = "boomtown.echo-webkom.no"
custom_domain = true

[dev]
port = 8004

[[durable_objects.bindings]]
name = "COUNTER"
class_name = "RegistrationCounter"

[[migrations]]
tag = "v1"
new_classes = ["RegistrationCounter"]
