#:schema node_modules/wrangler/config-schema.json
name = "ratelimit"
main = "src/index.ts"
compatibility_date = "2024-04-03"

compatibility_flags = [ "nodejs_compat" ]

#logpush = true
workers_dev = false

[[routes]]
pattern = "ratelimit.echo-webkom.no"
custom_domain = true

[dev]
port = 8005
