name: 🧪 Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-crons:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: 🚚 Install dependencies
        run: pnpm install

      - name: 🧪 Run tests
        run: pnpm --filter=crons test

  test-kaffe:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: 🚚 Install dependencies
        run: pnpm install

      - name: 📝 Create .dev.vars
        working-directory: kaffe
        run: |
          echo "SECRET=foobar" > .dev.vars

      - name: 🧪 Run tests
        run: pnpm --filter=kaffe test

  test-echogram:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: 🚚 Install dependencies
        run: pnpm install

      - name: 📝 Create .dev.vars
        working-directory: echogram
        run: |
          echo "SECRET=foobar" > .dev.vars

      - name: 🧪 Run tests
        run: pnpm --filter=echogram test
