name: 🧪 Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: 🚚 Install dependencies
        run: pnpm install

      - name: 📝 Create .dev.vars
        run: echo "SECRET=foobar" > .dev.vars

      - name: 🧪 Run tests
        run: pnpm test
